### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by firestrife23** [interaapps/pastefy#30]
I can access pastefy just fine by going to http://192.168.0.10:9999, but I'm unable to access pastefy with NGINX reverse proxy and, I'm getting file download instead of rendered page... I never had this issue with other 70 containers. 

Here's snippet of my docker compose
```
   pastefy:
     image: interaapps/pastefy:latest
     container_name: pastefy
     ports:
       - "9999:80"
     environment:
       HTTP_SERVER_PORT: 80
       HTTP_SERVER_CORS: "*"
       DATABASE_DRIVER: mysql
       DATABASE_NAME: pastefy
       DATABASE_USER: pastefy
       DATABASE_PASSWORD: XXXXXX
       DATABASE_HOST: mariadb
       DATABASE_PORT: 3306
       SERVER_NAME: "https://pastefy.XXXXX.com"
```

Snippet of my NGINX reverse proxy

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name pastefy.XXXXXX.com;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    include /config/nginx/authelia-server.conf;

    location / {
        include /config/nginx/authelia-location.conf;
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app pastefy;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

    }
}
```

P.S. my nginx container can access any containers directly using the hostname without exposing external ports and the only thing being exposed to the internet is nginx's port 80 and 443.
